                                         /* Scale in the key of 1/1000 */

/*
   These are wavelengths -- if you delay this long,
   then toggle the speaker pin, you'll get approximate
   pitches.

   This is the 16-bit version.  The pitches get less accurate
   as they get higher, but not as bad as the 8-bit one.

   "x" denotes sharp.

   Can be generated by:
     import math
     scale = ['C', 'Cx', 'D', 'Dx', 'E', 'F', 'Fx', 'G', 'Gx', 'A', 'Ax', 'B']
